- fail: key not specified
  when: keyfile is not defined

- name: create user(s)
  action: user name={{ user }} group={{ group }} shell=/bin/bash uid={{ uid }}

- name: setup authorized key(s)
  action: authorized_key user={{ user }} key="{{ lookup('file', keyfile) }}"
